version: '3.8'

services:
  # Product Service
  product-service:
    build:
      context: ./services/product-service
      dockerfile: Dockerfile
    container_name: automernate-product-service
    ports:
      - "5001:5001"
    environment:
      - NODE_ENV=production
      - MONGO_URI=${MONGO_URI}
      - PRODUCT_SERVICE_PORT=5001
    networks:
      - automernate-network
    restart: unless-stopped

  # User Service
  user-service:
    build:
      context: ./services/user-service
      dockerfile: Dockerfile
    container_name: automernate-user-service
    ports:
      - "5002:5002"
    environment:
      - NODE_ENV=production
      - MONGO_URI=${MONGO_URI}
      - JWT_SECRET=${JWT_SECRET}
      - USER_SERVICE_PORT=5002
    networks:
      - automernate-network
    restart: unless-stopped

  # Order Service
  order-service:
    build:
      context: ./services/order-service
      dockerfile: Dockerfile
    container_name: automernate-order-service
    ports:
      - "5003:5003"
    environment:
      - NODE_ENV=production
      - MONGO_URI=${MONGO_URI}
      - JWT_SECRET=${JWT_SECRET}
      - ORDER_SERVICE_PORT=5003
    depends_on:
      - product-service
      - user-service
    networks:
      - automernate-network
    restart: unless-stopped

  # Payment Service
  payment-service:
    build:
      context: ./services/payment-service
      dockerfile: Dockerfile
    container_name: automernate-payment-service
    ports:
      - "5004:5004"
    environment:
      - NODE_ENV=production
      - PAYMENT_SERVICE_PORT=5004
      - RAZORPAY_KEY_ID=${RAZORPAY_KEY_ID}
      - RAZORPAY_KEY_SECRET=${RAZORPAY_KEY_SECRET}
    networks:
      - automernate-network
    restart: unless-stopped

  # Notification Service
  notification-service:
    build:
      context: ./services/notification-service
      dockerfile: Dockerfile
    container_name: automernate-notification-service
    ports:
      - "5005:5005"
    environment:
      - NODE_ENV=production
      - NOTIFICATION_SERVICE_PORT=5005
      - EMAIL_HOST=${EMAIL_HOST}
      - EMAIL_PORT=${EMAIL_PORT}
      - EMAIL_USER=${EMAIL_USER}
      - EMAIL_PASS=${EMAIL_PASS}
    networks:
      - automernate-network
    restart: unless-stopped

  # API Gateway
  api-gateway:
    build:
      context: ./services/api-gateway
      dockerfile: Dockerfile
    container_name: automernate-api-gateway
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - API_GATEWAY_PORT=5000
      - PRODUCT_SERVICE_URL=http://product-service:5001
      - USER_SERVICE_URL=http://user-service:5002
      - ORDER_SERVICE_URL=http://order-service:5003
      - PAYMENT_SERVICE_URL=http://payment-service:5004
      - NOTIFICATION_SERVICE_URL=http://notification-service:5005
    depends_on:
      - product-service
      - user-service
      - order-service
      - payment-service
      - notification-service
    networks:
      - automernate-network
    restart: unless-stopped

  # Frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: automernate-frontend
    ports:
      - "3000:80"
    depends_on:
      - api-gateway
    networks:
      - automernate-network
    restart: unless-stopped

networks:
  automernate-network:
    driver: bridge
