# AutoMERNate Frontend Deployment
# Author: Muhammad Bilal Raza Attari
# Kubernetes Deployment for React Frontend with Nginx

apiVersion: apps/v1
kind: Deployment
metadata:
  name: automernate-frontend
  namespace: default
  labels:
    app: automernate
    component: frontend
    author: muhammad-bilal-raza-attari
spec:
  replicas: 3
  selector:
    matchLabels:
      app: automernate
      component: frontend
  template:
    metadata:
      labels:
        app: automernate
        component: frontend
    spec:
      containers:
      - name: frontend
        image: mern-ecommerce-frontend:latest
        imagePullPolicy: IfNotPresent  # For Docker Desktop Kubernetes
        ports:
        - containerPort: 80
          name: http
        env:
        - name: REACT_APP_API_URL
          valueFrom:
            configMapKeyRef:
              name: automernate-config
              key: REACT_APP_API_URL
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 15
          periodSeconds: 10
          timeoutSeconds: 3
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5

---
apiVersion: v1
kind: Service
metadata:
  name: automernate-frontend-service
  namespace: default
  labels:
    app: automernate
    component: frontend
spec:
  type: NodePort
  selector:
    app: automernate
    component: frontend
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30300  # Accessible at <minikube-ip>:30300
    protocol: TCP
    name: http
