apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
  labels:
    app: order-service
    tier: backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
        tier: backend
    spec:
      containers:
      - name: order-service
        image: bilalrazaswe/automernate-order-service:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5003
        env:
        - name: NODE_ENV
          value: "production"
        - name: ORDER_SERVICE_PORT
          value: "5003"
        - name: MONGO_URI
          valueFrom:
            secretKeyRef:
              name: automernate-secret
              key: mongo-uri
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: automernate-secret
              key: jwt-secret
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: order-service
  labels:
    app: order-service
spec:
  type: NodePort
  selector:
    app: order-service
  ports:
  - port: 5003
    targetPort: 5003
    nodePort: 30003
    protocol: TCP
