apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-service
  labels:
    app: payment-service
    tier: backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: payment-service
  template:
    metadata:
      labels:
        app: payment-service
        tier: backend
    spec:
      containers:
      - name: payment-service
        image: bilalrazaswe/automernate-payment-service:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5004
        env:
        - name: NODE_ENV
          value: "production"
        - name: PAYMENT_SERVICE_PORT
          value: "5004"
        - name: RAZORPAY_KEY_ID
          valueFrom:
            secretKeyRef:
              name: automernate-secret
              key: razorpay-key-id
        - name: RAZORPAY_KEY_SECRET
          valueFrom:
            secretKeyRef:
              name: automernate-secret
              key: razorpay-key-secret
        resources:
          limits:
            memory: "256Mi"
            cpu: "250m"
---
apiVersion: v1
kind: Service
metadata:
  name: payment-service
  labels:
    app: payment-service
spec:
  type: NodePort
  selector:
    app: payment-service
  ports:
  - port: 5004
    targetPort: 5004
    nodePort: 30004
    protocol: TCP
