apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-service
  labels:
    app: product-service
    tier: backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: product-service
  template:
    metadata:
      labels:
        app: product-service
        tier: backend
    spec:
      containers:
      - name: product-service
        image: automernate-product:dev
        imagePullPolicy: Never
        ports:
        - containerPort: 5001
        env:
        - name: NODE_ENV
          value: "production"
        - name: PRODUCT_SERVICE_PORT
          value: "5001"
        - name: MONGO_URI
          valueFrom:
            secretKeyRef:
              name: automernate-secret
              key: mongo-uri
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: product-service
  labels:
    app: product-service
spec:
  type: NodePort
  selector:
    app: product-service
  ports:
  - port: 5001
    targetPort: 5001
    nodePort: 30001
    protocol: TCP
