name: Deploy Microservices

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push API Gateway
      uses: docker/build-push-action@v4
      with:
        context: ./services/api-gateway
        push: true
        tags: automernate/api-gateway:latest

    - name: Build and push User Service
      uses: docker/build-push-action@v4
      with:
        context: ./services/user-service
        push: true
        tags: automernate/user-service:latest

    - name: Build and push Product Service
      uses: docker/build-push-action@v4
      with:
        context: ./services/product-service
        push: true
        tags: automernate/product-service:latest

    - name: Build and push Order Service
      uses: docker/build-push-action@v4
      with:
        context: ./services/order-service
        push: true
        tags: automernate/order-service:latest

    - name: Build and push Payment Service
      uses: docker/build-push-action@v4
      with:
        context: ./services/payment-service
        push: true
        tags: automernate/payment-service:latest

    - name: Build and push Notification Service
      uses: docker/build-push-action@v4
      with:
        context: ./services/notification-service
        push: true
        tags: automernate/notification-service:latest

    - name: Deploy to Kubernetes
      run: |
        kubectl apply -f k8s/